server:
  port: 8080

spring:
  datasource:
    username: root
    password: 14020465
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/search_engine
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL55Dialect

    hibernate:
  sql:
    init:
      mode: always


indexing-settings:
  sites:
    - url: https://ipfran.ru/
      name: ipfran.ru
